version: '3.7'

services:
  mariadb:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /home/muhakose/data:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpsite

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.21-alpine
    volumes:
      - /home/muhakose/data:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - wpsite

networks:
  wpsite:
    name: wpsite

volumes:
  db_data:
