version: '3.7'

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wpsite

  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wpsite

  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - wpsite

networks:
  wpsite:
    name: wpsite

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/muhakose/data/db_data
      o: bind
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/muhakose/data/wp_data
      o: bind
