version: '3.7'

services:
  mariadb:
    build:
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wpsite
  wordpress:
    depends_on:
      - mariadb
    build:
      dockerfile: requirements/wordpress/Dockerfile
    volumes: ['/home/muhakose/data:/var/www/html']
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - wpsite


networks:
  wpsite:
    name: wpsite

volumes:
  db_data: