version: '3.7'

services:
  mariadb:
    build:
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wpsite
  wordpress:
    depends_on:
      - mariadb
    build:
      dockerfile: requirements/wordpress/Dockerfile
    ports:
      - '8000:80'
    restart: always
    volumes: ['/home/muhakose/data:/var/www/html']
    env_file:
      - .env
    networks:
      - wpsite
  nginx:
    build:
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - wpsite

networks:
  wpsite:
    name: wpsite

volumes:
  db_data: