version: '3.7'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/masum/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/masum/data/mariadb

secrets:
  db_root_password:
    file: ./../secrets/db_root_password.txt
  db_password:
    file: ./../secrets/db_password.txt

networks:
  inception:
    name: inception
    driver: bridge


services:
  nginx:
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress/.
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    secrets:
      - db_password
    restart: always
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb:42
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception
    restart: always
