version: '3.7'

services:
  mariadb:
    build:
      name: mariadb
      dockerfile: requirements/mariadb/Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wpsite
  wordpress:
    depends_on:
      - mariadb
    build:
      name: wordpress
      dockerfile: requirements/wordpress/Dockerfile
    ports:
      - '8000:80'
    restart: always
    volumes: ['/home/muhakose/data:/var/www/html']
    env_file:
      - .env
    networks:
      - wpsite


networks:
  wpsite:
    name: wpsite

volumes:
  db_data: