version: '3.7'

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    networks:
      - wpsite
  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    volumes: ['/home/muhakose/data:/var/www/html']
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - wpsite


networks:
  wpsite:
    name: wpsite

volumes:
  db_data: