version: '3.7'

volumes:
  db_data:
  wordpress_data:

secrets:
  db_root_password:
    file: ./../secrets/db_root_password.txt
  db_password:
    file: ./../secrets/db_password.txt

networks:
  wp-network:
    driver: bridge


services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/ssl:/etc/nginx/ssl
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - wp-network
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp-network
    secrets:
      - db_password
    ports:
      - "80:80"
  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - wp-network
    restart:
      always
