CREATE TABLE IF NOT EXISTS mysql.roles_mapping (
    Host CHAR(60) COLLATE utf8_bin NOT NULL DEFAULT '',
    User CHAR(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    Role CHAR(32) COLLATE utf8_bin NOT NULL DEFAULT '',
    Admin_option ENUM('N','Y') COLLATE utf8_bin NOT NULL DEFAULT 'N',
    DEFAULT_ROLE ENUM('N','Y') COLLATE utf8_bin NOT NULL DEFAULT 'N',
    PRIMARY KEY (Host, User, Role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Roles Mapping';

ALTER TABLE mysql.event
    MODIFY COLUMN definer varchar(93) NOT NULL DEFAULT '',
    MODIFY COLUMN sql_mode set('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','POSTGRESQL','ORACLE','MSSQL','DB2','MAXDB','NO_KEY_OPTIONS','NO_TABLE_OPTIONS','NO_FIELD_OPTIONS','MYSQL323','MYSQL40','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NO_AUTO_CREATE_USER','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','EMPTY_STRING_IS_NULL','SIMULTANEOUS_ASSIGNMENT') NOT NULL DEFAULT '';

FLUSH TABLES;
